package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class ConnectivityDataModel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int numberDaysWithoutConnection;
   private String severity;

   public ConnectivityDataModel()
   {
   }

   public int getNumberDaysWithoutConnection()
   {
      return this.numberDaysWithoutConnection;
   }

   public void setNumberDaysWithoutConnection(int numberDaysWithoutConnection)
   {
      this.numberDaysWithoutConnection = numberDaysWithoutConnection;
   }

   public java.lang.String getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(java.lang.String severity)
   {
      this.severity = severity;
   }

   public ConnectivityDataModel(int numberDaysWithoutConnection,
         java.lang.String severity)
   {
      this.numberDaysWithoutConnection = numberDaysWithoutConnection;
      this.severity = severity;
   }

}