package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ConnectivityDataModel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int numberDaysWithoutConnection;
   private philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel severity;

   public ConnectivityDataModel()
   {
   }

   public int getNumberDaysWithoutConnection()
   {
      return this.numberDaysWithoutConnection;
   }

   public void setNumberDaysWithoutConnection(int numberDaysWithoutConnection)
   {
      this.numberDaysWithoutConnection = numberDaysWithoutConnection;
   }

   public philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(
         philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel severity)
   {
      this.severity = severity;
   }

   public ConnectivityDataModel(
         int numberDaysWithoutConnection,
         philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel severity)
   {
      this.numberDaysWithoutConnection = numberDaysWithoutConnection;
      this.severity = severity;
   }

}