package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HeliumBoilOff implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Date")
   private java.util.Date date;
   @org.kie.api.definition.type.Label("BoilOff")
   private java.lang.Float boilOff;
   @org.kie.api.definition.type.Label("HeliumLevel")
   private java.lang.Float heliumLevel;
   @org.kie.api.definition.type.Label("HeliumUpperLevel")
   private java.lang.Float heliumUpperLevel;
   @org.kie.api.definition.type.Label("HeliumLowerLevel")
   private java.lang.Float heliumLowerLevel;
   @org.kie.api.definition.type.Label("NumDaysHelLvlConst")
   private int numDaysHelLvlConst;
   @org.kie.api.definition.type.Label("RefDate")
   private java.util.Date refDate;
   @org.kie.api.definition.type.Label("IsFrcBolOffVal")
   private java.lang.Boolean isFrcBolOffVal;

   public HeliumBoilOff()
   {
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.Float getBoilOff()
   {
      return this.boilOff;
   }

   public void setBoilOff(java.lang.Float boilOff)
   {
      this.boilOff = boilOff;
   }

   public java.lang.Float getHeliumLevel()
   {
      return this.heliumLevel;
   }

   public void setHeliumLevel(java.lang.Float heliumLevel)
   {
      this.heliumLevel = heliumLevel;
   }

   public java.lang.Float getHeliumUpperLevel()
   {
      return this.heliumUpperLevel;
   }

   public void setHeliumUpperLevel(java.lang.Float heliumUpperLevel)
   {
      this.heliumUpperLevel = heliumUpperLevel;
   }

   public java.lang.Float getHeliumLowerLevel()
   {
      return this.heliumLowerLevel;
   }

   public void setHeliumLowerLevel(java.lang.Float heliumLowerLevel)
   {
      this.heliumLowerLevel = heliumLowerLevel;
   }

   public int getNumDaysHelLvlConst()
   {
      return this.numDaysHelLvlConst;
   }

   public void setNumDaysHelLvlConst(int numDaysHelLvlConst)
   {
      this.numDaysHelLvlConst = numDaysHelLvlConst;
   }

   public java.util.Date getRefDate()
   {
      return this.refDate;
   }

   public void setRefDate(java.util.Date refDate)
   {
      this.refDate = refDate;
   }

   public java.lang.Boolean getIsFrcBolOffVal()
   {
      return this.isFrcBolOffVal;
   }

   public void setIsFrcBolOffVal(java.lang.Boolean isFrcBolOffVal)
   {
      this.isFrcBolOffVal = isFrcBolOffVal;
   }

   public HeliumBoilOff(java.util.Date date, java.lang.Float boilOff,
         java.lang.Float heliumLevel, java.lang.Float heliumUpperLevel,
         java.lang.Float heliumLowerLevel, int numDaysHelLvlConst,
         java.util.Date refDate, java.lang.Boolean isFrcBolOffVal)
   {
      this.date = date;
      this.boilOff = boilOff;
      this.heliumLevel = heliumLevel;
      this.heliumUpperLevel = heliumUpperLevel;
      this.heliumLowerLevel = heliumLowerLevel;
      this.numDaysHelLvlConst = numDaysHelLvlConst;
      this.refDate = refDate;
      this.isFrcBolOffVal = isFrcBolOffVal;
   }

}