package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HeliumBoiloff implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public HeliumBoiloff() {
    }

}