package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MRCoolingBoundry implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private int minValue;

   private int maxValue;

   public MRCoolingBoundry()
   {
   }

   public int getMinValue()
   {
      return this.minValue;
   }

   public void setMinValue(int minValue)
   {
      this.minValue = minValue;
   }

   public int getMaxValue()
   {
      return this.maxValue;
   }

   public void setMaxValue(int maxValue)
   {
      this.maxValue = maxValue;
   }

   public MRCoolingBoundry(int minValue, int maxValue)
   {
      this.minValue = minValue;
      this.maxValue = maxValue;
   }

}