package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class MRDeviceConfig implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String coolingCabinet;
   private java.lang.String magnetType;

   @org.kie.api.definition.type.Label("MagnetTypeCategory")
   private java.lang.String magnetTypeCategory;

   @org.kie.api.definition.type.Label(value = "MainSystemType")
   private java.lang.String mainSystemType;

   @org.kie.api.definition.type.Label(value = "HelUpperLim")
   private int helUpperLim;

   @org.kie.api.definition.type.Label(value = "HelVesselCapacity")
   private int helVesselCapacity;

   public MRDeviceConfig()
   {
   }

   public java.lang.String getCoolingCabinet()
   {
      return this.coolingCabinet;
   }

   public void setCoolingCabinet(java.lang.String coolingCabinet)
   {
      this.coolingCabinet = coolingCabinet;
   }

   public java.lang.String getMagnetType()
   {
      return this.magnetType;
   }

   public void setMagnetType(java.lang.String magnetType)
   {
      this.magnetType = magnetType;
   }

   public java.lang.String getMagnetTypeCategory()
   {
      return this.magnetTypeCategory;
   }

   public void setMagnetTypeCategory(java.lang.String magnetTypeCategory)
   {
      this.magnetTypeCategory = magnetTypeCategory;
   }

   public java.lang.String getMainSystemType()
   {
      return this.mainSystemType;
   }

   public void setMainSystemType(java.lang.String mainSystemType)
   {
      this.mainSystemType = mainSystemType;
   }

   public int getHelUpperLim()
   {
      return this.helUpperLim;
   }

   public void setHelUpperLim(int helUpperLim)
   {
      this.helUpperLim = helUpperLim;
   }

   public int getHelVesselCapacity()
   {
      return this.helVesselCapacity;
   }

   public void setHelVesselCapacity(int helVesselCapacity)
   {
      this.helVesselCapacity = helVesselCapacity;
   }

   public MRDeviceConfig(java.lang.String coolingCabinet,
         java.lang.String magnetType, java.lang.String magnetTypeCategory,
         java.lang.String mainSystemType, int helUpperLim, int helVesselCapacity)
   {
      this.coolingCabinet = coolingCabinet;
      this.magnetType = magnetType;
      this.magnetTypeCategory = magnetTypeCategory;
      this.mainSystemType = mainSystemType;
      this.helUpperLim = helUpperLim;
      this.helVesselCapacity = helVesselCapacity;
   }

}