package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class MRDeviceConfig implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String coolingCabinet;
   private java.lang.String magnetType;

   public MRDeviceConfig()
   {
   }

   public java.lang.String getCoolingCabinet()
   {
      return this.coolingCabinet;
   }

   public void setCoolingCabinet(java.lang.String coolingCabinet)
   {
      this.coolingCabinet = coolingCabinet;
   }

   public java.lang.String getMagnetType()
   {
      return this.magnetType;
   }

   public void setMagnetType(java.lang.String magnetType)
   {
      this.magnetType = magnetType;
   }

   public MRDeviceConfig(java.lang.String coolingCabinet,
         java.lang.String magnetType)
   {
      this.coolingCabinet = coolingCabinet;
      this.magnetType = magnetType;
   }

}