package philips.healthcare.radar.rules.mrpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MRMeasurementDataModel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("HeliumValue")
   private int mHeliumValue;

   @org.kie.api.definition.type.Label("RoomTemperatureValue")
   private int mRoomTemperatureValue;

   @org.kie.api.definition.type.Label("HeliumOOS")
   private java.lang.Boolean mIsHeliumOOS;

   private int HELIUMOOSLIMIT;

   public MRMeasurementDataModel()
   {
   }

   public int getmHeliumValue()
   {
      return this.mHeliumValue;
   }

   public void setmHeliumValue(int mHeliumValue)
   {
      this.mHeliumValue = mHeliumValue;
   }

   public int getmRoomTemperatureValue()
   {
      return this.mRoomTemperatureValue;
   }

   public void setmRoomTemperatureValue(int mRoomTemperatureValue)
   {
      this.mRoomTemperatureValue = mRoomTemperatureValue;
   }

   public java.lang.Boolean getmIsHeliumOOS()
   {
      return this.mIsHeliumOOS;
   }

   public void setmIsHeliumOOS(java.lang.Boolean mIsHeliumOOS)
   {
      this.mIsHeliumOOS = mIsHeliumOOS;
   }

   public int getHELIUMOOSLIMIT()
   {
      return this.HELIUMOOSLIMIT;
   }

   public void setHELIUMOOSLIMIT(int HELIUMOOSLIMIT)
   {
      this.HELIUMOOSLIMIT = HELIUMOOSLIMIT;
   }

   public MRMeasurementDataModel(int mHeliumValue, int mRoomTemperatureValue,
         java.lang.Boolean mIsHeliumOOS, int HELIUMOOSLIMIT)
   {
      this.mHeliumValue = mHeliumValue;
      this.mRoomTemperatureValue = mRoomTemperatureValue;
      this.mIsHeliumOOS = mIsHeliumOOS;
      this.HELIUMOOSLIMIT = HELIUMOOSLIMIT;
   }

}