package philips.healthcare.radar.rules.mrpostprocessrules;

import philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel

rule "HeliumOOS"
	when
		m :  MRMeasurementDataModel( mHeliumValue > MRMeasurementDataModel.HELIUMOOSLIMIT)
	then
		System.out.println("Helium out of spec");
		m.setmIsHeliumOOS(true);
		update(m);	
end

rule "HeliumNotOOS"
   when
        //conditions
        m : MRMeasurementDataModel( mHeliumValue <=  MRMeasurementDataModel.HELIUMOOSLIMIT)        
    then
        //actions
		System.out.println("Helium NOT out of spec");
		m.setmIsHeliumOOS(true);
		update(m);
end
