package philips.healthcare.radar.rules.mrpostprocessrules;

import philips.healthcare.radar.rules.mrpostprocessrules.MRCoolingBoundry;
import philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel;
import philips.healthcare.radar.rules.mrpostprocessrules.MRDeviceConfig;

rule "CoolingOOSSpec_CAB1_4k"
no-loop true
when
	$coolingBoundry: MRCoolingBoundry(deviceConfig.coolingCabinet.equals("Cab1") && 
					deviceConfig.coolingCabinet.equals("4k"));
then
	System.out.println("CoolingOOSSpec_CAB1_4k");
	$coolingBoundry.setMinValue(20);
	$coolingBoundry.setMaxValue(30);
	update($coolingBoundry);
end

rule "CoolingOOSSpec_CAB1_10K"
no-loop true
when
	$coolingBoundry: MRCoolingBoundry(deviceConfig.coolingCabinet.equals("Cab1") && 
					deviceConfig.coolingCabinet.equals("10k"));
then
	System.out.println("CoolingOOSSpec_CAB1_10k");
	$coolingBoundry.setMinValue(40);
	$coolingBoundry.setMaxValue(60);
	update($coolingBoundry);
end
