package philips.healthcare.radar.rules.mrpostprocessrules;

import philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel;

rule "Connectivity Rule Severity High"
no-loop true
	when 
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection >10)
	then
		$MRMeasurementDataModel.setConnectivitySeverity("High");
		update($MRMeasurementDataModel)
end

rule "Connectivity Rule Severity Medium"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection >= 4 && numberDaysWithoutConnection <= 10 )
	then
		$MRMeasurementDataModel.setConnectivitySeverity("Medium");
		update($MRMeasurementDataModel)
end

rule "Connectivity Rule Severity None"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection < 3)
	then		
		$MRMeasurementDataModel.setConnectivitySeverity("None");
		update($MRMeasurementDataModel)
end

