package philips.healthcare.radar.rules.mrpostprocessrules;

import philips.healthcare.radar.rules.mrpostprocessrules.MRMeasurementDataModel;

rule "Connectivity Rule Severity High"
no-loop true
	when 
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection >10)
	then
		System.out.println("Connectivity Rule Severity High");
		$MRMeasurementDataModel.setConnectivitySeverity("High");
		update($MRMeasurementDataModel)
end

rule "Connectivity Rule Severity Medium"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection >= 4 && numberDaysWithoutConnection <= 10 )
	then
		System.out.println("Connectivity Rule Severity Medium");
		$MRMeasurementDataModel.setConnectivitySeverity("Medium");
		update($MRMeasurementDataModel)
end

rule "Connectivity Rule Severity None"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(numberDaysWithoutConnection < 3)
	then		
		System.out.println("Connectivity Rule Severity None");
		$MRMeasurementDataModel.setConnectivitySeverity("None");
		update($MRMeasurementDataModel);
end

rule "Helium level rule Severity High"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(HeliumLevel < 35 	|| HeliumBoilOff > 0.9)
	then
	System.out.println("Helium level rule Severity High");
	$MRMeasurementDataModel.setHeliumSeverity("High");
	update($MRMeasurementDataModel);
end

rule "Helium level rule Severity Medium"
no-loop true
	when
		$MRMeasurementDataModel: MRMeasurementDataModel(HeliumLevel >= 35 && HeliumLevel <= 45 )
	then
	System.out.println("Helium level rule Severity Medium");
	$MRMeasurementDataModel.setHeliumSeverity("Medium");
	update($MRMeasurementDataModel);
end

rule "Boil-off Rule Severity High for Titan magnet type"
no-loop true
	when
	$MRMeasurementDataModel: MRMeasurementDataModel(MRDeviceConfig.MagnetType == "Titan" && LongTermBoilOffMlPerHr > 250 )
	then
	System.out.println("Boil-off Rule Severity High for Titan magnet type");
	$MRMeasurementDataModel.setHeliumSeverity("High");
	update($MRMeasurementDataModel);
end

rule "Boil-off Rule Severity Medium for Titan magnet type"
no-loop true
	when
	$MRMeasurementDataModel: MRMeasurementDataModel(MRDeviceConfig.MagnetType == "Titan" && LongTermBoilOffMlPerHr >=200 && LongTermBoilOffMlPerHr <= 200)
	then
	System.out.println("Boil-off Rule Severity Medium for Titan magnet type");
	$MRMeasurementDataModel.setHeliumSeverity("Medium");
	update($MRMeasurementDataModel);
end

rule "Boil-off Rule Severity High for F2000 magnet type"
no-loop true
	when
	$MRMeasurementDataModel: MRMeasurementDataModel(MRDeviceConfig.MagnetType == 	"F2000" && LongTermBoilOffMlPerHr > 150 )
	then
	System.out.println("Boil-off Rule Severity High for F2000 magnet type");
	$MRMeasurementDataModel.setHeliumSeverity("High");
	update($MRMeasurementDataModel);
end

rule "Boil-off Rule Severity Medium for F2000 magnet type"
no-loop true
	when
	$MRMeasurementDataModel: MRMeasurementDataModel(MRDeviceConfig.MagnetType == 	"F2000" && LongTermBoilOffMlPerHr >= 100 && LongTermBoilOffMlPerHr <= 150 )
	then
	System.out.println("Boil-off Rule Severity Medium for F2000 magnet type");
	$MRMeasurementDataModel.setHeliumSeverity("Medium");
	update($MRMeasurementDataModel);
end

rule "Boil-off Rule for REX magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule for REX magnet type");
end

rule "Boil-off Rule Severity High for REX magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity High for REX magnet type");
end

rule "Boil-off Rule Severity Medium for REX magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity Medium for REX magnet type");
end

rule "Boil-off Rule for HFO magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule for HFO magnet type");
end

rule "Boil-off Rule Severity High for HFO magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity High for HFO magnet type");
end

rule "Boil-off Rule Severity Medium for HFO magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity Medium for HFO magnet type");
end

rule "Boil-off Rule for WA30T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule for WA30T magnet type");
end

rule "Boil-off Rule Severity High for WA30T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity High for WA30T magnet type");
end

rule "Boil-off Rule Severity Medium for WA30T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity Medium for WA30T magnet type");
end

rule "Boil-off Rule for WA15T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule for WA15T magnet type");
end

rule "Boil-off Rule Severity High for WA15T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity High for WA15T magnet type");
end

rule "Boil-off Rule Severity Medium for WA15T magnet type"
no-loop true
	when
	then
	System.out.println("Boil-off Rule Severity Medium for WA15T magnet type");
end

rule "Helium 4k magnet pressure rule severity high"
no-loop true
	when
	then
	System.out.println("Helium 4k magnet pressure rule severity high");
end

rule "Helium 10k magnet pressure rule severity high"
no-loop true
	when
	then
	System.out.println("Helium 10k magnet pressure rule severity high");
end

rule "Helium 4k magnet pressure rule severity medium"
no-loop true
	when
	then
	System.out.println("Helium 4k magnet pressure rule severity medium");
end

rule "Helium 10k magnet pressure rule severity medium"
no-loop true
	when
	then
	System.out.println("Helium 10k magnet pressure rule severity medium");
end

rule "Performance Rule Severity High"
no-loop true
	when
	then
	System.out.println("Performance Rule Severity High");
end

rule "Performance Rule Severity None"
no-loop true
	when
	then
	System.out.println("Performance Rule Severity None");
end

rule "HW/SW Errors Rule Severity High"
no-loop true
	when
	then
	System.out.println("HW/SW Errors Rule Severity High");
end

rule "HW/SW Errors Rule Severity None"
no-loop true
	when
	then
	System.out.println("HW/SW Errors Rule Severity None");
end

rule "Cooling Rule Severity High"
no-loop true
	when
	then
	System.out.println("Cooling Rule Severity High");
end

rule "Cooling Rule Severity None"
no-loop true
	when
	then
	System.out.println("Cooling Rule Severity None");
end

rule "IQT Quality Assurance High"
no-loop true
	when
	then
	System.out.println("IQT Quality Assurance High");
end

rule "IQT Quality Assurance None"
no-loop true
	when
	then
	System.out.println("IQT Quality Assurance None");
end