package philips.healthcare.radar.rules.cvpostprocessrules;

import philips.healthcare.radar.rules.cvpostprocessrules.CDF;
import philips.healthcare.radar.rules.cvpostprocessrules.Event;

rule "LicenseError"
	when
		CDF ($events : events)
		Event(eventID == "00001" && category == "Error") from $events
	then
		System.out.println("License error found...");
end

rule "StartUpError"
	when
		CDF ($events : events)
		Event(eventID == "00002" && category == "Error") from $events
	then
		System.out.println("StartUpError found...");
end

rule "Abnormal"
	when
		CDF ($events : events)
		$e1 : Event(eventID == "00005" && category == "information") from $events
		$e2: Event( this after $e1, (eventID == "00004" && category == "information")) from $events
	then
		System.out.println("Abnormal found...");
end


