package philips.healthcare.radar.rules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CVEvents implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CVEvents() {
    }

}