package philips.healthcare.radar.rules.cvpostprocessrules;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CDF implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public CDF() {
    }

}