package demo.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MRMeasurementData implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public MRMeasurementData() {
    }

}