package demo.sample;

/**
 * This class was automatically generated by the data modeler tool.
 */

public static class MRMeasurementData {
    	public static  final int HELIUMOOS = 25;
    	public static final int ROOMTEMPERATUREUPPERBOUNDRY = 30;
    	
    	private int mHeliumValue;
    	private int mRoomTemperatureValue;
    	private int mIsHeliumOOS;
    	
    	public void SetHeliumValue(int value)
    	{
    		this.mHeliumValue = value;
    	}
    	
    	public void SetClimateTeperatureValue(int value)
    	{
    		this.mRoomTemperatureValue = value;
    	}
    	
    	public int GetHeliumValue()
    	{
    		return this.mHeliumValue;
    	}
    	
    	public int GetRoomTemperature()
    	{
    		return this.mRoomTemperatureValue;
    	}
    	
    	public void SetHeliumOOS(int value)
    	{
    		this.mIsHeliumOOS = value;
    	} 
    	
    	public int GetHeliumOOS()
    	{
    		return mIsHeliumOOS;
    	}
    }